apiVersion: v1
kind: Service
metadata:
  name: react-backend
spec:
  type: NodePort
  selector:
    app: react-backend
  ports:
    - port: 30336
      protocol: TCP
      targetPort: 5050
      nodePort: 30336