apiVersion: v1
kind: Service
metadata:
  name: react-backend
  namespace: react
spec:
  type: ClusterIP
  selector:
    app: react-backend
  ports:
    - port: 5050
      protocol: TCP
      targetPort: 5050